### ISSUE TITLE
incorrect colorbox instructions

### ISSUE THREAD

**Issue by BuffaloRob** [learn-co-curriculum/react-dynamic-components-lab#1]
ColorBox instructions say:
if the opacity value is greater than or equal to 0.1:

but tests won't pass unless value used is >= 0.2, this value is also used in the solution

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @BuffaloRob.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
