### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by developerjigr** [learn-co-curriculum/react-dynamic-components-lab#2]
Tests are broken

**Comment by maxwellbenton** [comment]
Thank you for providing feedback, @developerjigr.

We have taken a look at this lesson and did not see that any tests were broken specifically. As per the readme, the Comment component file is missing and must be created before anything will work.

We have, however, updated the materials to include a blank Comment file, which will cause the tests to run without passing and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
