### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by moresmiles** [learn-co-curriculum/react-dynamic-components-lab#3]
There is a typo I believe at the end of the third paragraph of the Introduction section.

> All of the css has been provided, as well as a good amount of starter code. The general structure has already been provided - you are to pick up where the code leaves off and make both the Comment and the ColorBox components behave dynamically**.f**

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @moresmiles.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
