### ISSUE TITLE
Learn is not completing although tests passed

### ISSUE THREAD

**Issue by ChristopherBlack22** [learn-co-curriculum/react-dynamic-components-lab#48]
### Canvas Link

https://learning.flatironschool.com/courses/1883/assignments/125692?module_item_id=259605

### Concern

All tests are marked as passed but terminal stalls thereby no posting a completed lab.

**Comment by ihollander** [comment]
Hi @ChristopherBlack22 - thanks for flagging! I was able to reproduce this issue, and will update the test script to fix it.
